-- ==========================================
-- 🌍 3. COUNTRIES (РЕКВИЗИТЫ)
-- ==========================================

DROP TABLE IF EXISTS public.country_bank_details CASCADE;

CREATE TABLE public.country_bank_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name TEXT NOT NULL UNIQUE,       -- Название
    country_code TEXT NOT NULL,              -- Код (RU, KZ...)
    currency TEXT NOT NULL,                  -- Валюта (RUB...)
    bank_details TEXT NOT NULL,              -- Реквизиты (текст)
    exchange_rate FLOAT DEFAULT 1.0,         -- Курс
    is_active BOOLEAN DEFAULT TRUE,          
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Пресеты
INSERT INTO public.country_bank_details (country_name, country_code, currency, bank_details, exchange_rate) VALUES
('Россия', 'RU', 'RUB', E'Сбербанк: 2202 2002 0000 0000\nСБП: +7 900 000-00-00\nПолучатель: Дроп И.', 0.0105),
('Казахстан', 'KZ', 'KZT', E'Kaspi Gold: 4400 4301 0000 0000\nПолучатель: Дроп К.', 0.0022),
('Узбекистан', 'UZ', 'UZS', E'Uzcard: 8600 0000 0000 0000\nПолучатель: Дроп У.', 0.000081),
('Crypto (USDT)', 'US', 'USDT', E'TRC20: TJsSd....(кошелек)...\nNetwork: TRON', 1.0);

-- RLS
ALTER TABLE public.country_bank_details ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for countries" ON public.country_bank_details FOR ALL USING (true) WITH CHECK (true);