-- ==========================================
-- 💰 5. DEPOSITS (ЗАЯВКИ НА ДЕП)
-- ==========================================

DROP TABLE IF EXISTS public.deposit_requests CASCADE;

CREATE TABLE public.deposit_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    worker_id BIGINT,                         -- ID воркера
    
    amount_local FLOAT NOT NULL,              -- Сумма в руб/тенге
    amount_usd FLOAT NOT NULL,                -- Сумма в USD
    currency TEXT NOT NULL,                   -- RUB/KZT
    method TEXT NOT NULL,                     -- card/sbp
    
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    processed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_deposits_worker_status ON public.deposit_requests(worker_id, status);

-- RLS
ALTER TABLE public.deposit_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for deposits" ON public.deposit_requests FOR ALL USING (true) WITH CHECK (true);