-- ==========================================
-- 🎁 6. PROMOS (УМНЫЙ СКРИПТ: СОЗДАНИЕ + ОБНОВЛЕНИЕ)
-- ==========================================

-- 1. Создаем таблицу кодов (Если её нет)
CREATE TABLE IF NOT EXISTS public.promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,            
    reward_amount FLOAT NOT NULL,         
    max_activations INT DEFAULT 100,      
    current_activations INT DEFAULT 0,    
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. МИГРАЦИЯ: Добавляем колонки, если таблица была старой
-- (Эти команды сработают, только если колонок еще нет)

-- Добавляем creator_id (кто создал промокод)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='promo_codes' AND column_name='creator_id') THEN
        ALTER TABLE public.promo_codes 
        ADD COLUMN creator_id BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL;
    END IF;
END $$;

-- Добавляем description (описание)
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='promo_codes' AND column_name='description') THEN
        ALTER TABLE public.promo_codes ADD COLUMN description TEXT;
        -- Заполняем пустые описания для старых записей
        UPDATE public.promo_codes SET description = 'Системный промокод' WHERE description IS NULL;
    END IF;
END $$;

-- 3. Создаем таблицу активаций (Кто ввел код)
CREATE TABLE IF NOT EXISTS public.user_promos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    promo_id BIGINT NOT NULL REFERENCES public.promo_codes(id) ON DELETE CASCADE,
    activated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, promo_id)             
);

-- ==========================================
-- ⚙️ ЛОГИКА (ТРИГГЕРЫ И ФУНКЦИИ)
-- ==========================================

-- 4. Функция счетчика (обновляет кол-во использований)
CREATE OR REPLACE FUNCTION increment_promo_activations()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.promo_codes 
    SET current_activations = current_activations + 1
    WHERE id = NEW.promo_id;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 5. Триггер (Сначала удаляем старый, чтобы не дублировался)
DROP TRIGGER IF EXISTS tr_increment_promo ON public.user_promos;

CREATE TRIGGER tr_increment_promo
AFTER INSERT ON public.user_promos
FOR EACH ROW EXECUTE FUNCTION increment_promo_activations();

-- ==========================================
-- 🛡 БЕЗОПАСНОСТЬ (RLS)
-- ==========================================

ALTER TABLE public.promo_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_promos ENABLE ROW LEVEL SECURITY;

-- Безопасное создание политик (пропускает, если уже есть)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'promo_codes' AND policyname = 'Enable all for promos') THEN
        CREATE POLICY "Enable all for promos" ON public.promo_codes FOR ALL USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'user_promos' AND policyname = 'Enable all for user_promos') THEN
        CREATE POLICY "Enable all for user_promos" ON public.user_promos FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- ==========================================
-- 🧪 ТЕСТОВЫЕ ДАННЫЕ
-- ==========================================

-- Вставляем промокод, только если такого кода еще нет (ON CONFLICT DO NOTHING)
INSERT INTO public.promo_codes (code, reward_amount, max_activations, description) 
VALUES ('BONUS2025', 1000, 10000, 'Новогодний бонус')
ON CONFLICT (code) DO NOTHING;

SELECT 'Таблицы промокодов готовы и обновлены! 🎁' as status;