-- ==========================================
-- ⚙️ 2. SETTINGS (НАСТРОЙКИ)
-- ==========================================

DROP TABLE IF EXISTS public.settings CASCADE;

CREATE TABLE public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_username TEXT DEFAULT 'Support_Agent', -- Юзернейм ТП
    bank_details TEXT DEFAULT 'Реквизиты не указаны', -- Банковские реквизиты
    min_deposit FLOAT DEFAULT 10.0,                -- Мин. деп
    is_tech_work BOOLEAN DEFAULT FALSE,            -- Тех. работы
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Дефолтные значения
INSERT INTO public.settings (support_username, bank_details, min_deposit) VALUES ('ManagerSupport', 'Реквизиты не указаны', 500);

-- RLS
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);